name: JSON check

on:
  push:
    paths:
      - "**.json"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check JSON syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
      - name: Validate appsettings.json
        uses: docker://orrosenblatt/validate-json-action:latest
        with:
          SCHEMA: ./appsettings.schema.json
          JSONS: ./appsettings.json
      - name: Validate countries.json
        uses: docker://orrosenblatt/validate-json-action:latest
        with:
          SCHEMA: ./countries.schema.json
          JSONS: ./countries.json
      - name: Validate tipkit.json
        uses: docker://orrosenblatt/validate-json-action:latest
        with:
          SCHEMA: ./tipkit/tipkit.schema.json
          JSONS: ./tipkit/tipkit.json
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
